[package]
name = "launch_operation_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.6.0"
iced = { version = "0.13.1", features = ["tokio"] }
log = "0.4.26"
env_logger = "0.11.6"
rand = "0.9.0"
axum = { version = "0.8.4", features = [ "ws" ]}
tokio = { version = "1.47.1", features = [ "full" ] }
chrono = "0.4.42"
