name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libudev-dev
    - name: Build code_generator
      run: (cd code_generator; cargo build --verbose)
    - name: Run tests code_generator
      run: (cd code_generator; cargo test --verbose)
    - name: Build launch_operation_gui
      run: (cd launch_operation_gui; cargo build --verbose)
    - name: Run tests launch_operation_gui
      run: (cd launch_operation_gui; cargo test --verbose)
    - name: Run Cliant
      run: (cd cliant; chmod +x run.sh; ./run.sh -t)
